### ISSUE TITLE
Rating of sentences and quotes

### ISSUE THREAD

**Issue by grumpyp** [grumpyp/NLP-quote-maker#3]
_Please run the @functio_

Hello,

I was thinking about our rating algorithm and what functions we could use for the first MVP model.

Right now I applied two functions to evaluate the **sentiment and the entities** of a sentence.

The sentiment-function returns 4 values which I inspected a bit closer:
 `{'neg': 0.0, 'neu': 0.724, 'pos': 0.276, 'compound': 0.7269}`

In my eyes it is crucial to use the first three values, as compound is already set by a algorithm behind the library. For more informations see https://stackoverflow.com/questions/40325980/how-is-the-vader-compound-polarity-score-calculated-in-python-nltk

I was checking 5 different sentences and got the following output

![grafik](https://user-images.githubusercontent.com/75830792/121649749-2a18af80-ca99-11eb-9daf-8ee2ba66f075.png)

In my oppinion the neutral score should rate lower than the negative and the positive so I setup the following rating formula:
`self.sentiment_scores["neg"] * -1 + self.sentiment_scores["neu"] * 0.3 + self.sentiment_scores["pos"]`

**rating = - negative score + neutral score x 0,3 + positive score** 

My next thought was, that we could add the entities.
So in case we simulate the algorithm, the first question would be if there are some **entity matches**
if yes, compare the rating of the quotes to the rating of the sentence, if the rating difference is really small (we need to find out a suitable value), use these quotes before checking other possible matches without an entity match.

I added 5 random quotes to the code as well, to give you a first insight about similarity and possible matches.

![grafik](https://user-images.githubusercontent.com/75830792/121650856-4cf79380-ca9a-11eb-9c66-a86955e9eb31.png)

### Todo: 

- [ ] Review more than 5 sentences to get a first feedback about the rating and the parameter settings
- [ ] Add entity rating/algorithm to fully review 

-> Finally agree on a first MVP rating algorithm

Lets discuss

**Comment by jedi3nigma** [comment]
thanks setting this initial summary! i thinks its good to customize our own weighting considering some sentences clearly have some type of polarity yet are weighted too much on the neutral score.

on your comparison approach, so what i'm getting at is, for example, assuming the 3rd sentence and 5th quote had a very similar rating_test score & both contained 'DATE' entities, then our output to that sentence would be that quote then?

**Comment by gitforharpreet** [comment]
Thanks for taking lead and adding your thoughts. This would be a good start for MVP
